[build]
  command = "make setup-js build-prod"
  publish = "_site"


# The `activesupport` gem needs this from v7 on.
[context.production]
  environment = { RUBY_VERSION = "2.7.0" }

[context.deploy-preview]
  environment = { RUBY_VERSION = "2.7.0" }
