# Public repos owned by the current user along with metadata including topics.
# Until paging is implemented in this project, this stops after 100 repos. Rather than going by name, I go
# by updated date so recent activity shows up.
query ReposWithTopics {
	viewer {
		login
		repositories(first: 100, ownerAffiliations: OWNER, privacy: PUBLIC, orderBy: { field: UPDATED_AT, direction: DESC }) {
			nodes {
				# Metadata
				name
				url
				description
				# Dates
				createdAt
				updatedAt
				pushedAt
				# Counts
				stargazers {
					totalCount
				}
				forkCount
				defaultBranchRef {
					commits: target {
						... on Commit {
							history(first: 1) {
								totalCount
							}
						}
					}
				}
				# Topic labels. Not available in REST API so the main reason for GQL for this project.
				repositoryTopics(first: 100) {
					nodes {
						topic {
							name
							stargazers {
								totalCount
							}
							viewerHasStarred
						}
						url
					}
				}
			}
		}
	}
}
