# Public repos owned by the current user along with metadata including topics.
query ReposWithTopics {
    viewer {
        login
        repositories(first: 100, ownerAffiliations: OWNER, privacy: PUBLIC, orderBy: { field: NAME, direction: ASC }) {
            nodes {
                # Metadata
                name
                url
                description
                # Dates
                createdAt
                updatedAt
                pushedAt
                # Counts
                stargazers {
                    totalCount
                }
                forkCount
                defaultBranchRef {
                    commits: target {
                        ... on Commit {
                            history(first: 1) {
                                totalCount
                            }
                        }
                    }
                }
                # Topic labels
                repositoryTopics(first: 100) {
                    nodes {
                        topic {
                            name
                            stargazers {
                                totalCount
                            }
                            viewerHasStarred
                        }
                        url
                    }
                }
            }
        }
    }
}
