    name: Scheduled Netlify deploy

    on:
      # schedule:
      #  - cron: "0 0 * * *"
      workflow_dispatch:
      
    jobs:
      deploy:
        name: Deploy

        runs-on: ubuntu-latest

        steps:
          - name: Request hook
            run: curl -d '' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK_ID }}
